PSST/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PSST.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
    [Required(ErrorMessage = "THE FLAVOR MUST BE NAMED!!!")]
    public string FlavorDescription { get; set; }
    public List<FlavorTreat> JoinEntities { get; }
    public ApplicationUser User { get; set; }
  }
}

PSST/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PSST.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PSST.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PSSTContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PSSTContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public async Task<ActionResult> Index()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Flavor> model = _db.Flavors.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Flavor flavor, int TreatId)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        flavor.User = currentUser;
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
    
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Flavor thisFlavor = _db.Flavors
                                .Include(flavor => flavor.JoinEntities)
                                .ThenInclude(join => join.Treat)
                                .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      _db.Flavors.Update(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors
                              .Include(flavor => flavor.JoinEntities)
                              .ThenInclude(join => join.Treat)
                              .FirstOrDefault(flavors => flavors.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatDescription");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int treatId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats
                                    .FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flavor.FlavorId));
      #nullable disable
      if (joinEntity == null && treatId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flavor.FlavorId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PSST/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using PSST.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace PSST.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PSSTContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PSSTContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public async Task<ActionResult> Index()
    {
      string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      List<Treat> model = _db.Treats.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }
    
    [HttpPost]
    public async Task<ActionResult> Create(Treat treat, int FlavorId)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        treat.User = currentUser;
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }
    
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
                          .Include(treat => treat.JoinEntities)
                          .ThenInclude(join => join.Flavor)
                          .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      if (!ModelState.IsValid)
      {
          return View(treat);
      }
      
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats
                            .Include(treat => treat.JoinEntities)
                            .ThenInclude(join => join.Flavor)
                            .FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorDescription");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
      #nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreats
                                    .FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.FlavorTreats.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }  

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreats.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PSST/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PSST.Models.Flavor

<h4>Add a Treat to this Flavor: @Html.DisplayFor(model => model.FlavorDescription)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Save" class="btn btn-primary btn-sm" />
}
<br>
<p>@Html.ActionLink("Back to list", "Index")</p>

PSST/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PSST.Models.Flavor

<h4>Add a new Flavor:</h4>
<div class="col">
  <p>@Html.ValidationMessageFor(model => model.FlavorDescription, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
  <hr/ >
  <p>FLAVOR NAME:</p>
  @using (Html.BeginForm())
  {
    @Html.TextBoxFor(model => model.FlavorDescription, new { @class = "form-control"})
    <br>
    <input type="submit" value="Add new Flavor" class="btn btn-primary btn-sm"/>
  }
  <br>
  <p class="btn btn-primary btn-sm">@Html.ActionLink("Show all Flavors", "Index")</p>
</div>

PSST/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PSST.Models.Flavor

<h2>Are you sure you want to delete this flavor?</h2>

@Html.DisplayNameFor(model => model.FlavorDescription): @Html.DisplayFor(model => model.FlavorDescription)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" class="btn btn-primary btn-sm" />
}
@Html.ActionLink("Back to Flavor List", "Index")

PSST/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using PSST.Models
@model PSST.Models.Flavor

<h2>Flavor Details</h2>
<hr />
<h3>Flavor Name: @Html.DisplayFor(model => model.FlavorDescription)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>WHY HAVE YOU NOT ADD A TREAT TO THIS FLAVOR? WHY?</p>
}
else
{
  <h4>This Flavor has the following Treats matched:</h4>
  <ul>
    @foreach(FlavorTreat join in Model.JoinEntities)
    {
      <li>Treat: @join.Treat.TreatDescription</li>
      @using (Html.BeginForm("DeleteJoin", "Treats"))
      {
        @Html.Hidden("joinId", @join.FlavorTreatId)
        <input type="submit" value="Delete" class="btn btn-primary btn-sm"/>
      }
    }
  </ul>
}
<p>@Html.ActionLink("Add a Treat to this Flavor", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Delete Flavor", "Delete", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>
<p>@Html.ActionLink("Back to list", "Index", "Flavors")</p>

PSST/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PSST.Models.Flavor

<h4>Edit this Flavor: @Html.DisplayFor(model => model.FlavorDescription)</h4>
<div class="col">
<p>@Html.ValidationMessageFor(model => model.FlavorDescription, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorDescription, new { htmlAttributes = new { @class = "form-label"}})
    @Html.EditorFor(model => model.FlavorDescription, new { htmlAttributes = new { @class = "form-control"}})
    <br>
    <input type="submit" value="Save" class="btn btn-primary btn-sm"  />
  }
  <br>
  <p>@Html.ActionLink("Back to Flavor list", "Index")</p>
</div>

PSST/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PSST.Models;

<h1>Pierre's Flavors for: @User.Identity.Name</h1>

@if (@Model.Count == 0)
{
  <h3>No flavors have been added yet!</h3>
} 
<ul>
  @foreach(Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.FlavorDescription}", "Details", new { id = flavor.FlavorId })</li>
  }
</ul>

<p>@Html.ActionLink("Add a new flavor", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>